version: '3.8'

services:
  db:
    image: postgres
    container_name: hotel-postgres
    restart: always
    environment:
      POSTGRES_DB: hotel
      POSTGRES_USER: postgresW
      POSTGRES_PASSWORD: postgresW
    ports:
      - "5432:5432"
    volumes:
      - hotel_pgdata:/var/lib/postgresql/data

volumes:
  hotel_pgdata:
